version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    depends_on:
      - redis
    restart: 'on-failure'
    environment: # //TODO: check workings its or no! //TODO
      - ASPNETCORE_ENVIRONMENT
      - DB_CONNECTION_STRING
      - BOT_URL
      - AUTH_KEY
    networks:
      - proxy
    # Traefik labels
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.rule=${TRAEFIK_HOST}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.Cache-Control=no-cache"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.Pragma=no-cache"

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    networks:
      - proxy
    
volumes:
  redis-data:
  redis-conf:

networks:
  proxy:
    external: true